#!/usr/bin/env sh
conf="${0%/*}/myocr.conf"
echo "Файл параметров: $conf"
source_file="${1}"
if [[ ! -e "${source_file}" ]] 
then
   printf "Отсутствует файл $source_file\n"
#   exit 1   
fi

write_conf() {
	echo "$1"="$2" 
} >>$conf	






if [[ ! -e ${0%/*}/myocr.conf ]] 
then
  write_conf ocr_output pdf
  write_conf ocr_O 2
  write_conf ocr_lang rus
  write_conf ocr_jbig2 ""
  write_conf ocr_clean "--clean"
  write_conf ocr_clean_final ""
  write_conf ocr_deskew "--deskew"
  write_conf ocr_unpapper ""
  write_conf ocr_force_ocr ""
  write_conf ocr_skip_text ""
  write_conf ocr_remove_background ""
  write_conf ocr_rotate_pages ""
  write_conf ocr_redo_ocr ""
  write_conf ocr_pages ""
fi



create_cmd() {
  echo ocrmypdf --output-type=$ocr_output -O $ocr_O -l ${ocr_lang} ${ocr_jbig2} $ocr_clean $ocr_clean_final $ocr_deskew  $ocr_force_ocr $ocr_skip_text $ocr_remove_background $ocr_rotate_pages $ocr_redo_ocr "$source_file" "${source_file%.*}"_ocr.pdf
}

edit_arg() {
  printf "\n${1}?: "
  read val 
  args=$(sed -e "s/^${2}.*/${2}=${val}/" $conf) 
  echo -e "$args" > $conf
}

set_conf_arg() {
	args=$(sed -e "s/^${1}=.*/${1}=${2}/" $conf)
        echo -e "$args" > $conf 

}

set_clear_arg() {
printf "\n${1}[y/N]?: "
  read -r -n 1 sel
  if [[ "$sel" = "y" ]]; then
	set_conf_arg $2 $3
  else
	set_conf_arg $2 ''
 fi	

}

changearg() {

    printf "\nИзменить параметры:\n"
    printf "  'l'- язык распознавания: (${ocr_lang:-нет})\n"
    printf "  'o'- оптимизация pdf: (${ocr_O:-нет})\n"
    printf "  'f'- выходной формат: (${ocr_output:-нет})\n"
    printf "  'j'- сжатие jbig2-lossy: (${ocr_jbig2:-нет})\n"
    printf "  'c'- очистка перед OCR: (${ocr_clean:-нет})\n"
    printf "  'i'- очистка выходных изображений: (${ocr_clean_final:-нет})\n"
    printf "  'd'- устранение перекоса: (${ocr_deskew:-нет})\n"
    printf "  '1'- одинарный макет: (${ocr_unpapper:-нет})\n"
    printf "  '2'- двойной макет: (${ocr_unpapper:-нет})\n"
    printf "  'g'- форсировать OCR: (${ocr_force_ocr:-нет})\n"
    printf "  't'- не распознавать страницы с текстовым слоем: (${ocr_skip_text:-нет})\n"
    printf "  'b'- удалить фон: (${ocr_remove_background:-нет})\n"
    printf "  'r'- автоматический поворот страниц: (${ocr_rotate_pages:-нет})\n"
    printf "  '-'- удалить слой OCR: (${ocr_redo_ocr:-нет})\n"
    printf "  'p'- номера страниц: (${ocr_pages:-нет})\n"
    printf "  'u'- аргументы unpapper: (${ocr_unpapper:-нет})\n"
    read -r -n 1 -p ":" sel
    if [[ "$sel" = "l" ]];  then
#	printf "\nЯзык распознавания?: "
#	read arg   
#	textconf=$(sed -e '/^ocr_lang=/d' "$conf")
#    	echo -e "$textconf" > "$conf"
#  	echo ocr_lang="$arg" >> "$conf"
        edit_arg "Язык распознавания" ocr_lang
    elif [[ "$sel" = "o" ]];  then
        edit_arg "Параметр оптимизации[0-3]"  ocr_O
    elif [[ "$sel" = "f" ]];  then
        edit_arg "Выходной формат[pdf,pdfa,pdfa-1,pdfa-2,pdfa-3]" ocr_output
    elif [[ "$sel" = "j" ]];  then
	set_clear_arg "Применять сжатие jbig2" ocr_jbig2 '--jbig2-lossy'
    elif [[ "$sel" = "c" ]];  then
	set_clear_arg "Очистка перед OCR" ocr_clean '-clean'
    elif [[ "$sel" = "i" ]];  then
	set_clear_arg "Очистка на выходе" ocr_clean_final '--clean-final'
    elif [[ "$sel" = "d" ]];  then
	set_clear_arg "Устанять перекос" ocr_dewkew '--deskew'
    elif [[ "$sel" = "g" ]];  then
	set_clear_arg "Форсировать OCR" ocr_force_ocr '--force-ocr'
    elif [[ "$sel" = "1" ]];  then
	set_clear_arg "Одинарнный макет" ocr_unpapper '--layout-single'
    elif [[ "$sel" = "2" ]];  then
	set_clear_arg "Двойной макет" ocr_unpapper '--layout-double'
    elif [[ "$sel" = "t" ]];  then
	    set_clear_arg "Старый текстовый слой (где есть)" ocr_skip_text '--skip-text'
    elif [[ "$sel" = "b" ]];  then
	set_clear_arg "Удалить фон" ocr_remove_background '--remove-background'
    elif [[ "$sel" = "r" ]];  then
	set_clear_arg "Автоматический поворот" ocr_rotate_pages '--rotate-pages'
    elif [[ "$sel" = "-" ]];  then
	set_clear_arg "Удалить OCR" ocr_redo_ocr '--redo-ocr'
    elif [[ "$sel" = "p" ]];  then
        edit_arg "Номера страниц[Например:1-3,7,9,11-14]"  ocr_pages
    elif [[ "$sel" = "u" ]];  then
        edit_arg "Параметры unpapper"  ocr_unpapper
    fi  

}

while true
do
  source $conf 
  cmd=$(create_cmd)
#  echo $cmd
  printf "\n'r'-выполнить:\n"
  printf  " $cmd\n" 
  printf "'c'-изменить параметры 'q'-выход\n"
  printf "[по умолчанию 'q'-выход]:"
  read -r -n 1 sel
  if [[ "$sel" = "r" ]];  then
   $cmd 
  elif [[ "$sel" = "c" ]];  then
   changearg	  
  else	  
     break
 fi    
done	

