#!/usr/bin/env sh

# Description: Sets the xdg-open's default application for the current entry's file
#              type. ${XDG_DATA_DIRS} and ${XDG_DATA_HOME} are set to the recommended
#              defaults if unset, as specified in XDG Base Directory Specification
#              - http://specifications.freedesktop.org/basedir-spec/.
#
# Dependencies: xdg-utils, fzf or dmenu (GUI)
#
# Shell: POSIX compliant
# Author: lwnctd

# set to 1 to enable GUI apps


selfile="$1"
ftype=$(xdg-mime query filetype "$1")

if [ -z "$ftype" ]; then
    exit 1
fi

dirs=${XDG_DATA_DIRS:-/usr/local/share:/usr/share}
dirs=${dirs}:${XDG_DATA_HOME:-$HOME/.local/share}:

while [ -n "$dirs" ]; do
    d=${dirs%%:*}
    if [ -n "$d" ] && [ -d "$d"/applications ]; then
        set -- "$@" "$d"/applications
    fi
    dirs=${dirs#*:}
done

app=$(find "$@" -iname '*.desktop' -exec grep "$ftype" {} + \
    |cut -f 1 -d ":" \
    |sed -e 's;.*/\(.*\)$;\1;' \
    | rofi -dmenu) 
#    |sort  \

if [ -n "$app" ]; then
    xdg-mime default "${app}" "$ftype"
    xdg-open "$selfile"
fi
